### PR TITLE
Disable button after submitting

### PR DESCRIPTION
**Pull request by francomendoza**
which caused [this bug](https://app.clubhouse.io/lingolive/story/22324/bug-i-am-unable-to-continue-to-the-learning-objectives-page-it-just-returns-to-the-task-assessment-page-after-i-press-submit)

### CODE REVIEW

**Comment by edwinthinks** [comment]
@francomendoza on failure of the outcome of the submit, does the disable button go back to not disabled?

**Comment by francomendoza** [comment]
@edwinthinks depends on the type of failure. if the there is some error on the server, the page will 500, if there is just no response ever from the server, than this will stay disabled.  I'm not sure how requests time outs are handled by browser, but this is a similar problem that we have on all of our AJAX submits where we disable the button.

**Comment by edwinthinks** [comment]
@francomendoza gotcha. So in the case for the bug fix its a page load so we shouldn't have any trouble doing this change here. 

In terms of the AJAX calls, we usually handle them a level above right? For example, the Learning Objectives page has some logic that already handles the disabling of the button. Just wondering if this change would affect things.

**Comment by francomendoza** [comment]
@edwinthinks correct

So in react pages that use ll-button, we don't use the "submit" attribute on the WC that would trigger this behavior, so there is no cause for concern for those pages.

**Pull request merged**
